embeddings:
    - name: "alabama"
      boundary: /Users/noah/Dev/geovibes/geometries/alabama.geojson
      dbs:
          alabama_google: /Users/noah/Dev/geovibes/local_databases/alabama_google.db

options:
    ee_basemap_start_date: "2024-01-01"
    ee_basemap_end_date: "2025-01-01"
    verbose: true
    local_download_path: /Users/noah/Dev/geovibes/local_downloads
